# Generated by Django 3.2.7 on 2021-09-02 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_rename_message_messagechat'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReponseChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('reponse', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.messagechat')),
            ],
            options={
                'ordering': ('date_added',),
            },
        ),
    ]
